//splash screen
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const AUTH_NAVIGATION = 'AUTH_NAVIGATION';

//navigation
export const PUBLIC_NAVIGATION = 'PUBLIC_NAVIGATION';
export const AUTH_NAVIGATION = 'AUTH_NAVIGATION';
export const BOTTOM_TAB_NAVIGATION = 'BOTTOM_TAB_NAVIGATION'

//screen
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const NEAR_BY_SCREEN = 'NEAR_BY_SCREEN';
export const FLOATING_MENU = 'FLOATING_MENU';
export const BENEFICIARY_SCREEN = 'BENEFICIARY_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';